stages:
        - test
        - docs

cache:
        paths:
        - vendor/
test:
        image: $DOCKERHOST/devpeak-php
        script:
                - composer install --no-suggest --no-progress --quiet
                - phpdbg -qrr vendor/bin/phpunit --colors=never
                - vendor/bin/pdepend --jdepend-xml=build/logs/jdepend.xml --jdepend-chart=build/dependencies.svg --overview-pyramid=build/overview-pyramid.svg DevpeakIT,public
                - vendor/bin/phpcs --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=ruleset.xml --ignore=provider --extensions=php DevpeakIT public tests
                - curl --max-time 5 -X POST -d 'project_id='"$CI_PROJECT_ID"'' -d 'project_namespace='"$CI_PROJECT_NAMESPACE"'' -d 'project_name='"$CI_PROJECT_NAME"'' -d 'metric=checkstyle_violations' -d 'value='"$(cat build/logs/checkstyle.xml |grep "<error"|wc -l)"'' $BUILDMETRICS_URL
                - vendor/bin/phpmd DevpeakIT xml unusedcode,codesize --reportfile build/logs/pmd.xml --exclude provider --ignore-violations-on-exit
                - vendor/bin/phploc --count-tests --exclude provider --log-csv build/logs/phploc.csv --log-xml build/logs/phploc.xml DevpeakIT/ public/ tests/
                - curl --max-time 5 -X POST -d 'project_id='"$CI_PROJECT_ID"'' -d 'project_namespace='"$CI_PROJECT_NAMESPACE"'' -d 'project_name='"$CI_PROJECT_NAME"'' -d 'metric=lines_of_code' -d 'value='"$(grep "<loc>" build/logs/phploc.xml |cut -f2 -d">"|cut -f1 -d"<")"'' $BUILDMETRICS_URL
                - vendor/bin/phpcpd --log-pmd build/logs/pmd-cpd.xml --exclude provider DevpeakIT/ public/ || true
                - curl --max-time 5 -X POST -d 'project_id='"$CI_PROJECT_ID"'' -d 'project_namespace='"$CI_PROJECT_NAMESPACE"'' -d 'project_name='"$CI_PROJECT_NAME"'' -d 'metric=phpcpd_blocks' -d 'value='"$(grep "<duplication" build/logs/pmd-cpd.xml |wc -l)"'' $BUILDMETRICS_URL
                - vendor/bin/phpmetrics --report-html=build/phpmetrics.html --report-xml=build/phpmetrics.xml --violations-xml=build/violations.xml --chart-bubbles=build/chart.svg --extensions=php --offline --excluded-dirs="vendor|provider" DevpeakIT
                - vendor/bin/phan -o build/phan.txt || true
                - curl --max-time 5 -X POST -d 'project_id='"$CI_PROJECT_ID"'' -d 'project_namespace='"$CI_PROJECT_NAMESPACE"'' -d 'project_name='"$CI_PROJECT_NAME"'' -d 'metric=phanissues' -d 'value='"$(cat build/phan.txt|wc -l)"'' $BUILDMETRICS_URL
        artifacts:
                when: always
                expire_in: 1month
                paths:
                - build
                - coverage
                - clover.xml
phpdox:
        image: $DOCKERHOST/devpeak-php
        stage: docs
        script:
                - composer install
                - vendor/bin/phpdox
