stages:
  - test
  - analysis

cache:
  paths:
    - vendor/
test:
  image: $BUILDIMAGE

  before_script:
    - apt-get update && apt-get install -y php-sqlite3 php-ast
    - composer global require pdepend/pdepend squizlabs/php_codesniffer phpmd/phpmd phploc/phploc sebastian/phpcpd phan/phan
    - mkdir -p build/logs
  script:
    - cp -n .env.example .env
    - npm install
    - npm run production
    - composer install --no-suggest --no-progress
    - php artisan key:generate
    - php artisan test --parallel --coverage-text --log-junit junit-report.xml --coverage-cobertura cobertura-report.xml
  artifacts:
    when: always
    expire_in: 1month
    paths:
      - build
      - coverage
      - clover.xml
    reports:
      junit: junit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura-report.xml

sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: $SONARHOST
    SONAR_ANALYSIS_MODE: publish
  script:
    - /usr/bin/sonar-scanner-run.sh

security-check:
  image: $BUILDIMAGE
  stage: analysis
  script:
    - composer global require sensiolabs/security-checker
    - ~/.composer/vendor/bin/security-checker security:check


phpmetrics:
  image: $BUILDIMAGE
  stage: analysis
  dependencies:
    - test
  script:
    - composer global require phpmetrics/phpmetrics
    - ~/.composer/vendor/bin/phpmetrics --report-html=phpmetrics/html --report-xml=phpmetrics/xml --violations-xml=phpmetrics/violations.xml --chart-bubbles=phpmetrics/chart.svg --extensions=php --offline app
  artifacts:
    when: on_success
    expire_in: 1month
    paths:
      - phpmetrics
