stages:
  - test
  - analysis

cache:
  paths:
    - vendor/

test:
  image: $BUILDIMAGE

  before_script:
    - apt-get update && apt-get install -y php-sqlite3 php-ast
    - composer global require pdepend/pdepend squizlabs/php_codesniffer phpmd/phpmd phploc/phploc sebastian/phpcpd phan/phan
    - mkdir -p build/logs
  script:
    - cp -n .env.example .env
    - npm install
    - npm run production
    - composer install --no-suggest --no-progress
    - php artisan key:generate
    - php artisan test --parallel --coverage-text --log-junit junit-report.xml --coverage-cobertura cobertura-report.xml
  artifacts:
    when: always
    expire_in: 1month
    paths:
      - build
      - coverage
      - clover.xml
    reports:
      junit: junit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura-report.xml

security-check:
  image: $BUILDIMAGE
  stage: analysis
  script:
    - local-php-security-checker
